server:
  port: 8080
  servlet:
    context-path: /project-management-backend

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/PROJECT_MANAGEMENT
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: ${DDL_CREATE:none}

    show-sql: true
#    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  security:
    filter:
      order: 10

